#nullable enable

using System;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;

namespace Diz.App.Winforms;

/// <summary>
/// THE LIVE-TYPING FIX (new-ui plan, "Live typing bug", 2026-07-19).
///
/// Symptom: with DIZ_LABEL_EDITOR=avalonia, every non-text interaction in the Avalonia label
/// editor works (selection, buttons, Enter/Escape/Delete, Ctrl+A) but TYPING does nothing.
///
/// Proven cause (instrumented; full evidence + provenance in docs/diz/new-ui-plan.md, "Live typing
/// bug"). The process's single Win32 message loop is owned by WinForms' Application.Run. In
/// System.Windows.Forms.Application.ThreadContext.PreTranslateMessage, for a message whose target
/// HWND is NOT a WinForms control (Control.FromChildHandle returns null for a foreign Avalonia
/// top-level), WinForms falls into IsDialogMessage(GetAncestor(hwnd, GA_ROOT), msg):
///   - For WM_KEYDOWN, IsDialogMessage internally TranslateMessage+DispatchMessage's the key, so
///     Avalonia's WndProc runs (KeyDown fires) AND a WM_CHAR is synthesized -- then returns true.
///   - For the resulting WM_CHAR, IsDialogMessage treats it as dialog-mnemonic input and CONSUMES
///     it (Avalonia answers no WM_GETDLGCODE / DLGC_WANTCHARS, so it is not offered to the window),
///     so the WM_CHAR never reaches Avalonia's WndProc and no TextInput is ever raised.
/// Net effect: non-character virtual keys keep working (selection, Enter/Escape/Delete, arrows,
/// Ctrl+A) while every printable keystroke is silently eaten -- typing is dead. The headless
/// preview harness drives Avalonia's input API directly, bypassing Win32, which is why it passes.
///
/// Fix: an IMessageFilter installed on the WinForms UI thread. WinForms runs every filter's
/// PreFilterMessage BEFORE the IsDialogMessage branch. For keyboard-range messages
/// (WM_KEYFIRST..WM_KEYLAST) targeting an Avalonia top-level window we TranslateMessage+DispatchMessage
/// ourselves and return true, preempting IsDialogMessage entirely. WM_KEYDOWN still reaches Avalonia
/// (we dispatch it) AND its WM_CHAR is generated by our TranslateMessage and, on the next pump,
/// dispatched by us to the Avalonia HWND -> Avalonia raises TextInput.
///
/// This is a hand-port of Avalonia's own WinFormsAvaloniaMessageFilter (upstream PR #20814, issue
/// #16046). We cannot reference Avalonia.Win32.Interoperability (plan decision 4) nor pull WinForms
/// into Diz.Ui.Avalonia (must stay platform-free), so the ~20-line filter lives here in the WinForms
/// app layer instead. Upstream's WindowImpl.IsOurWindowGlobal is internal, so Avalonia HWNDs are
/// identified by window class ("Avalonia-<guid>") rather than that seam.
///
/// Provenance / further reading:
///   - Upstream fix (maintainer-authored, ships in Avalonia.Win32.Interoperability >= 12.0.0-rc2):
///     https://github.com/AvaloniaUI/Avalonia/pull/20814
///     https://github.com/AvaloniaUI/Avalonia/blob/main/src/Windows/Avalonia.Win32.Interoperability/WinForms/WinFormsAvaloniaMessageFilter.cs
///   - Exact-symptom upstream issue (mouse works, typing dead, WinForms host):
///     https://github.com/AvaloniaUI/Avalonia/issues/16046
///   - The WinForms code that eats the keys (PreTranslateMessage -> IsDialogMessage fallback):
///     https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/System/Windows/Forms/Application.ThreadContext.cs
///   - Why IsDialogMessage consuming a message means it never reaches TranslateMessage:
///     https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-isdialogmessagea
///
/// Scope guard: messages for WinForms windows (or any non-Avalonia HWND) are ignored (return
/// false -> normal WinForms handling), so the WinForms main window's own typing is untouched. Only
/// installed when the Avalonia backend is selected. Respects plan decision 4: no UI interop, no
/// embedding -- this only re-pumps whole-window Win32 keyboard messages.
/// </summary>
internal sealed class AvaloniaKeyboardMessageFilter : IMessageFilter
{
    private const int WM_KEYFIRST = 0x0100;
    private const int WM_KEYLAST = 0x0109; // through WM_UNICHAR

    public bool PreFilterMessage(ref Message m)
    {
        if (m.Msg < WM_KEYFIRST || m.Msg > WM_KEYLAST)
            return false;
        if (!IsAvaloniaWindow(m.HWnd))
            return false;

        var native = new NativeMessage
        {
            hwnd = m.HWnd,
            message = (uint)m.Msg,
            wParam = m.WParam,
            lParam = m.LParam,
        };

        // Same order a normal Win32 message loop uses: translate (WM_KEYDOWN -> queued WM_CHAR),
        // then dispatch to the target window procedure. Returning true tells WinForms this message
        // is fully handled, so it neither re-translates nor drops it.
        TranslateMessage(ref native);
        DispatchMessage(ref native);
        return true;
    }

    private static bool IsAvaloniaWindow(IntPtr hwnd)
    {
        if (hwnd == IntPtr.Zero)
            return false;
        var sb = new StringBuilder(64);
        var n = GetClassName(hwnd, sb, sb.Capacity);
        // Avalonia's Win32 backend registers window classes named "Avalonia-<guid>".
        return n > 0 && sb.ToString().StartsWith("Avalonia", StringComparison.Ordinal);
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct NativeMessage
    {
        public IntPtr hwnd;
        public uint message;
        public IntPtr wParam;
        public IntPtr lParam;
        public uint time;
        public int pt_x;
        public int pt_y;
    }

    [DllImport("user32.dll")]
    private static extern bool TranslateMessage(ref NativeMessage m);

    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    private static extern IntPtr DispatchMessage(ref NativeMessage m);

    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    private static extern int GetClassName(IntPtr hWnd, StringBuilder lpClassName, int nMaxCount);
}
