using Avalonia.Controls;

namespace Diz.Ui.Avalonia;

/// <summary>
/// The Avalonia progress popup window (new-ui plan step 6, Part C). Layout is in
/// ProgressWindow.axaml; this code-behind just exposes the imperative setters
/// AvaloniaProgressView drives (description, marquee/determinate, percent). The x:Name fields
/// (StatusText, Bar, PercentText) and InitializeComponent are generated by the Avalonia XAML
/// source generator -- never hand-write them (AVLN / source-generator suppression gotcha).
/// </summary>
internal sealed partial class ProgressWindow : Window
{
    public ProgressWindow()
    {
        InitializeComponent();
    }

    public void SetDescription(string? text) =>
        StatusText.Text = string.IsNullOrEmpty(text) ? "Please wait..." : text;

    public void SetMarquee(bool marquee)
    {
        Bar.IsIndeterminate = marquee;
        if (marquee)
            PercentText.Text = "";
    }

    public void SetProgress(int percent)
    {
        // determinate values are ignored while in marquee mode (no meaningful %).
        if (Bar.IsIndeterminate)
            return;

        Bar.Value = percent;
        PercentText.Text = $"{percent}%";
    }
}
