using Diz.Core.Interfaces;

namespace Diz.Core.model.snes;

public class SampleDataGenerationTag : IDataTag
{
    /// <summary>
    /// Store the original number of bytes generated by a sample ROM generator. 
    /// The sample data generator builds a full bank, but, it does so by padding up to the next bank size.
    /// This field stores the original number of bytes generated, before padding took place.
    ///
    /// This is useful info for some subsystems like the assembly exporter, which generates labels that
    /// might fall outside the range of the original sample data.
    ///
    /// If set to -1, no padding occured.
    /// Only sample data created by Diz will have this field. It does not need to be serialized.
    ///
    /// Don't use this field for anything that's actually important.
    /// </summary>
    public int OriginalRomSizeBeforePadding { get; init; } = -1;
}